name: 'Upload to PyScript.com'
description: 'Uploads your repository to PyScript.com as a new project.'
author: 'FabioRosado'
inputs:
  api_token:
    description: 'The API token for authentication'
    required: true
  project_id:
    description: 'The project id to upload the repository to.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Zip files
      uses: montudor/action-zip@v1
      with:
        args: zip -r archive.zip .

    - name: Send to PyScript.com
      shell: bash
      run: |
        curl -X POST "https://pyscript-dev.com/api/projects/${{ inputs.project_id }}/files?archive=true&overwrite=true" \
        -H "Authorization: Bearer ${{ inputs.api_token }}" \
        -F "file=@archive.zip" \

branding:
  icon: 'package'
  color: 'blue'
