name: 'Upload to PyScript.com'
description: 'Uploads your repository to PyScript.com as a new project.'
author: 'FabioRosado'
inputs:
  api_token:
    description: 'The API token for authentication'
    required: true
  project_id:
    description: 'The project id to upload the repository to.'
    required: true
  api_domain:
    description: 'The domain of the API endpoint. Defaults to "pyscript.com".'
    required: false
    default: 'pyscript.com'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Zip files
      uses: montudor/action-zip@v1
      with:
        # By default we are ignore ALL . folders in the repo
        args: zip -r archive.zip . -x ".*/*"

    - name: Send to PyScript.com
      shell: bash
      run: |
        response=$(curl -s -w "%{http_code}" -o response_body.txt -X POST "https://${{ inputs.api_domain }}.com/api/projects/${{ inputs.project_id }}/files?archive=true&overwrite=true" \
        -H "Authorization: Bearer ${{ inputs.api_token }}" \
        -F "file=@archive.zip")

        # Check if the response status code is less than 300
        if [ "$response" -ge 300 ]; then
          echo "Error: Received HTTP status code $response"
          echo "Response body:"
          cat response_body.txt
          exit 1
        fi

        echo "File uploaded successfully."

branding:
  icon: 'package'
  color: 'blue'
